/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car.glb -t 
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { ContactShadows, useGLTF } from '@react-three/drei'

export function Car({renderOrder = 1}: {renderOrder?: number}) {
  const { scene } = useGLTF('/assets/model/car.glb');

  return (
    <group rotation={[0, Math.PI, 0]} renderOrder={renderOrder}>
      <primitive object={scene.clone()} scale={0.5} />
    </group>
  )
}

useGLTF.preload('/assets/model/car.glb')
